# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dalton Ma
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Dalton's Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
theme: jekyll-theme-cs50

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3
exclude: ["README.md"]

collections:
  author:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title


defaults:
  - scope:
      path: ""
      type: "author"
    values:
      layout: "author"

algolia: false

cs50:
  tz: America/Chicago